## @section Common parameters

## @param host The hostname used to access the grafana externally (defaults to 'grafana' subdomain for the tenant host).
host: ""

## @param metricsStorages [array] Configuration of metrics storage instances
##
metricsStorages:
- name: shortterm
  retentionPeriod: "3d"
  deduplicationInterval: "5m"
  storage: 10Gi
  storageClassName: ""
- name: longterm
  retentionPeriod: "14d"
  deduplicationInterval: "15s"
  storage: 10Gi
  storageClassName: ""

## @param logsStorages [array] Configuration of logs storage instances
##
logsStorages:
- name: generic
  retentionPeriod: "1"
  storage: 10Gi
  storageClassName: replicated

## Configuration for Alerta
## @param alerta.storage Persistent Volume size for alerta database
## @param alerta.storageClassName StorageClass used to store the data
##
alerta:
  storage: 10Gi
  storageClassName: ""

  alerts:
    ## @param alerta.alerts.telegram.token telegram token for your bot
    ## @param alerta.alerts.telegram.chatID specify multiple ID's separated by comma. Get yours in https://t.me/chatid_echo_bot
    ## example:
    ##   telegram:
    ##     token: "7262461387:AAGtwq16iwuVtWtzoN6TUEMpF00fpC9Xz34"
    ##     chatID: "-4520856007"
    ##
    telegram:
      token: ""
      chatID: ""

## Configuration for Grafana
## @param grafana.db.size Persistent Volume size for grafana database
grafana:
  db:
    size: 10Gi
