apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  name: {{ include "etcd.serviceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.clientPort }}
      name: client
    - port: {{ .Values.peerApiPort }}
      name: peer
    - port: {{ .Values.metricsPort }}
      name: metrics
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
