kubeapps:

  postgresql:
    enabled: false

  packaging:
    helm:
      enabled: false
    flux:
      enabled: true

  dashboard:
    customStyle: |
      #serviceaccount-selector {
        display: none;
      }
