## @section Common parameters

## @param replicas Number of ingress-nginx replicas
##
replicas: 2

## @param externalIPs [array] List of externalIPs for service.
## Optional. If not specified will use LoadBalancer service by default.
## 
## e.g:
## externalIPs:
##   - "11.22.33.44"
##   - "11.22.33.45"
##   - "11.22.33.46"
##
externalIPs: []

## @param whitelist List of client networks
## Example:
## whitelist:
## - "1.2.3.4"
## - "10.100.0.0/16"
whitelist: []

## @param clouflareProxy Restoring original visitor IPs when Cloudflare proxied is enabled
clouflareProxy: false

## @param dashboard Should ingress serve Cozystack service dashboard
dashboard: false

## @param cdiUploadProxy Should ingress serve CDI upload proxy
cdiUploadProxy: false
