annotations:
  artifacthub.io/license: AGPL-3.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://fluxcd.control-plane.io/operator
    - name: Chart Source
      url: https://github.com/controlplaneio-fluxcd/charts
    - name: Upstream Project
      url: https://github.com/controlplaneio-fluxcd/flux-operator
apiVersion: v2
appVersion: v0.15.0
description: 'A Helm chart for deploying the Flux Operator. '
home: https://github.com/controlplaneio-fluxcd
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/flux/icon/color/flux-icon-color.png
keywords:
- flux
- fluxcd
- gitops
kubeVersion: '>=1.22.0-0'
maintainers:
- email: flux-enterprise@control-plane.io
  name: ControlPlane Flux Team
name: flux-operator
sources:
- https://github.com/controlplaneio-fluxcd/flux-operator
- https://github.com/controlplaneio-fluxcd/charts
type: application
version: 0.15.0
