cilium:
  sctp:
    enabled: true
  autoDirectNodeRoutes: false
  bpf:
    masquerade: false
  cni:
    chainingMode: generic-veth
    chainingTarget: kube-ovn
    customConf: true
    configMap: cni-configuration
  routingMode: native
  enableIPv4Masquerade: false
  enableIPv6Masquerade: false
  enableIdentityMark: false
  enableRuntimeDeviceDetection: true
  forceDeviceDetection: true
  devices: "ovn0 genev_sys_6081"
