{{- if and .Values.helmController.create}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: helm-controller
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
    {{- with .Values.helmController.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: helm-controller
spec:
  {{- if kindIs "invalid" .Values.helmController.replicas }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.helmController.replicas  }}
  {{- end}}
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      {{- with .Values.helmController.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: helm-controller
{{ with .Values.helmController.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      automountServiceAccountToken: {{ .Values.helmController.serviceAccount.automount }}
    {{- if .Values.helmController.initContainers}}
      initContainers:
        {{- toYaml .Values.helmController.initContainers | nindent 8}}
    {{- end}}
      containers:
      - args:
        {{- if .Values.multitenancy.enabled }}
        - --no-cross-namespace-refs=true
        - --default-service-account={{ .Values.multitenancy.defaultServiceAccount | default "default"  }}
        {{- end}}
        {{- if .Values.notificationController.create }}
        - --events-addr=http://notification-controller.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- end}}
        - --watch-all-namespaces={{ .Values.watchAllNamespaces }}
        - --log-level={{ .Values.logLevel | default "info" }}
        - --log-encoding=json
        - --enable-leader-election
        {{- range .Values.helmController.container.additionalArgs }}
        - {{ . }}
        {{- end}}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.helmController.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ template "template.image" .Values.helmController }}
        {{- if .Values.helmController.imagePullPolicy }}
        imagePullPolicy: {{ .Values.helmController.imagePullPolicy }}
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        {{- with .Values.helmController.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.helmController.securityContext }}
        securityContext: {{ toYaml .Values.helmController.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        volumeMounts:
        - mountPath: /tmp
          name: temp
        {{- if .Values.helmController.volumeMounts }}
        {{- toYaml .Values.helmController.volumeMounts | nindent 8 }}
        {{- end}}
      {{- if .Values.helmController.priorityClassName }}
      priorityClassName: {{ .Values.helmController.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.helmController.podSecurityContext }}
      securityContext: {{ toYaml .Values.helmController.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: helm-controller
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: temp
      {{- if .Values.helmController.volumes }}
      {{- toYaml .Values.helmController.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.helmController.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.helmController.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.helmController.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
