{{- if and .Values.imageAutomationController.create}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: image-automation-controller
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
    {{- with .Values.imageAutomationController.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: image-automation-controller
spec:
  {{- if kindIs "invalid" .Values.imageAutomationController.replicas }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.imageAutomationController.replicas  }}
  {{- end}}
  selector:
    matchLabels:
      app: image-automation-controller
  template:
    metadata:
      {{- with .Values.imageAutomationController.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: image-automation-controller
{{ with .Values.imageAutomationController.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      automountServiceAccountToken: {{ .Values.imageAutomationController.serviceAccount.automount }}
      {{- if .Values.imageAutomationController.initContainers}}
      initContainers:
        {{- toYaml .Values.imageAutomationController.initContainers | nindent 8}}
      {{- end}}
      containers:
      - args:
        {{- if .Values.multitenancy.enabled }}
        - --no-cross-namespace-refs=true
        {{- end}}
        {{- if .Values.notificationController.create }}
        - --events-addr=http://notification-controller.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- end}}
        - --watch-all-namespaces={{ .Values.watchAllNamespaces }}
        - --log-level={{ .Values.logLevel | default "info" }}
        - --log-encoding=json
        - --enable-leader-election
        {{- range .Values.imageAutomationController.container.additionalArgs }}
        - {{ . }}
        {{- end}}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.imageAutomationController.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ template "template.image" .Values.imageAutomationController }}
        {{- if .Values.imageAutomationController.imagePullPolicy }}
        imagePullPolicy: {{ .Values.imageAutomationController.imagePullPolicy }}
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        {{- with .Values.imageAutomationController.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.imageAutomationController.securityContext }}
        securityContext: {{ toYaml .Values.imageAutomationController.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        volumeMounts:
        - mountPath: /tmp
          name: temp
        {{- if .Values.imageAutomationController.volumeMounts }}
        {{- toYaml .Values.imageAutomationController.volumeMounts | nindent 8 }}
        {{- end}}
      {{- if .Values.imageAutomationController.priorityClassName }}
      priorityClassName: {{ .Values.imageAutomationController.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.imageAutomationController.podSecurityContext }}
      securityContext: {{ toYaml .Values.imageAutomationController.podSecurityContext | nindent 8 }}
      {{- else }}
      securityContext:
        fsGroup: 1337
      {{- end}}
      serviceAccountName: image-automation-controller
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: temp
      {{- if .Values.imageAutomationController.volumes }}
      {{- toYaml .Values.imageAutomationController.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.imageAutomationController.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageAutomationController.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageAutomationController.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
