{{- if .Values.sourceController.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: source-controller
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
    {{- with .Values.sourceController.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  name: source-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-controller
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.sourceController.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: source-controller
{{ with .Values.sourceController.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      automountServiceAccountToken: {{ .Values.sourceController.serviceAccount.automount }}
      {{- if .Values.sourceController.initContainers}}
      initContainers:
        {{- toYaml .Values.sourceController.initContainers | nindent 8}}
      {{- end}}
      containers:
      - args:
        {{- if .Values.notificationController.create }}
        - --events-addr=http://notification-controller.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- end}}
        - --watch-all-namespaces={{ .Values.watchAllNamespaces }}
        - --log-level={{ .Values.logLevel | default "info" }}
        - --log-encoding=json
        - --enable-leader-election
        - --storage-path=/data
        - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.{{ .Values.clusterDomain | default "cluster.local" }}.
        {{- range .Values.sourceController.container.additionalArgs }}
        - {{ . }}
        {{- end}}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.sourceController.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ template "template.image" .Values.sourceController }}
        {{- if .Values.sourceController.imagePullPolicy }}
        imagePullPolicy: {{ .Values.sourceController.imagePullPolicy }}
        {{- else }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- with .Values.sourceController.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.sourceController.securityContext }}
        securityContext: {{ toYaml .Values.sourceController.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
        {{- if .Values.sourceController.volumeMounts }}
        {{- toYaml .Values.sourceController.volumeMounts | nindent 8 }}
        {{- end}}
      {{- if .Values.sourceController.priorityClassName }}
      priorityClassName: {{ .Values.sourceController.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.sourceController.podSecurityContext }}
      securityContext: {{ toYaml .Values.sourceController.podSecurityContext | nindent 8 }}
      {{- else }}
      securityContext:
        fsGroup: 1337
      {{- end}}
      serviceAccountName: source-controller
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
      {{- if .Values.sourceController.volumes }}
      {{- toYaml .Values.sourceController.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.sourceController.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sourceController.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sourceController.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
