{{- if .Values.addons.ingressNginx.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  labels:
    cozystack.io/repository: system
    coztstack.io/target-cluster-name: {{ .Release.Name }}
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: cozy-ingress-nginx
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-kubeconfig
  targetNamespace: cozy-ingress-nginx
  storageNamespace: cozy-ingress-nginx
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    ingress-nginx:
      fullnameOverride: ingress-nginx
      controller:
        kind: DaemonSet
        hostNetwork: true
        service:
          enabled: false
      nodeSelector:
        node-role.kubernetes.io/ingress-nginx: ""
  {{- if .Values.addons.ingressNginx.valuesOverride }}
  valuesFrom:
  - kind: Secret
    name: {{ .Release.Name }}-ingress-nginx-values-override
    valuesKey: values
  {{- end }}
  dependsOn:
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  - name: {{ .Release.Name }}-cilium
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.addons.ingressNginx.valuesOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ingress-nginx-values-override
stringData:
  values: |
    {{- toYaml .Values.addons.ingressNginx.valuesOverride | nindent 4 }}
{{- end }}
