apiVersion: v2
appVersion: v0.13.10
dependencies:
- condition: crds.enabled
  name: crds
  repository: ""
  version: 0.13.10
description: A network load-balancer implementation for Kubernetes using standard
  routing protocols
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
kubeVersion: '>= 1.19.0-0'
name: metallb
sources:
- https://github.com/metallb/metallb
type: application
version: 0.13.10
