
controller:
  plugin:
    image:
      pullPolicy: Always
      tag: edge

node:
  plugin:
    image:
      pullPolicy: Always
      tag: edge

  nodeSelector:
    node.cloudprovider.kubernetes.io/platform: nocloud

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
  - name: proxmox-data
    storage: data
    ssd: true
