apiVersion: v2
appVersion: v0.13.10
description: MetalLB CRDs
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
name: crds
sources:
- https://github.com/metallb/metallb
type: application
version: 0.13.10
